### ISSUE TITLE
Help! Doesn't work in CB 1.2.5

### ISSUE THREAD

**Issue by AngellitoX** [grandwazir/StarterKit#4]
Hey man, hello!

I have this problem...

I load the plugin, I put the items ingame as the tutorial says... But when I test it by joining with a new account, I don't get any item...

Why could be the problem?

Thanks by the way!

Greetings!

**Comment by grandwazir** [comment]
Your new account will only receive the kit in the following circumstances:
- The player has not joined the server before
- The player does not have a corresponding .dat file in your main world players folder.
- They have not joined since the last server restart.

Make sure all of the above are false and try again and see if the problem persists.

**Comment by michalpol** [comment]
I have same problem but i receive Armor items in wrong slots and not all: i set it to have full leather armor and i get leather boots at feet and leather leggings at chestplate slot.

**Comment by grandwazir** [comment]
I do not think this problems are related michalpol. Please make a separate ticket for your issue including a configuration that creates this problem.

**Comment by michalpol** [comment]
I've found solution for my problem as of now. I just removed my old datfile but had a plugin which restored inv from its own db and they interferred.
